### PR TITLE
Media controls

### PR DESCRIPTION
**Pull request by filiphanes**
Hi,
this should add media controls to source-switcher.
But I was not able to compile and test it according to instructions under OBS plugins.
Could you test it please or help me with compilation?

Solves https://github.com/exeldro/obs-source-switcher/issues/15

### CODE REVIEW

**Comment by exeldro** [comment]
You can download and test windows and linux build from the bottom of this page when logged in on GitHub:
https://github.com/exeldro/obs-source-switcher/actions/runs/11138311001

**Comment by exeldro** [comment]
I fixed the mac build in master

**Comment by filiphanes** [comment]
ok, tested on windows, works as needed.
Media controls pauses only timed switching, do you think it should pause Media state switching too?
Anything else before merge?

**Comment by filiphanes** [comment]
macOS arm64 version works same.

When paused it does not update slider position, but I think that is OBS who updates slider.

Maybe hotkey for play/pause?

**Comment by exeldro** [comment]
I plan to test the changes next week

**Pull request merged**
